#!/bin/bash

# Quick Start: Automação "Teve alteração?"

echo ""
echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║          🔄 AUTOMAÇÃO: TEVE ALTERAÇÃO? — QUICK START                      ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ Validando sistema..."
python3 ~/Scripts/test_auto_alteracao.py

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🎯 PRÓXIMOS PASSOS:"
echo ""
echo "  Opção A — Usar Webhook (Automático)"
echo "  ───────────────────────────────────"
echo "  1. Inicie o webhook:"
echo "     python3 ~/Scripts/webhook_auto_alteracao.py"
echo ""
echo "  2. Configure no ClickUp:"
echo "     Settings → Integrations → Webhooks → Create Webhook"
echo "     URL: http://localhost:5001/webhook/auto-alteracao"
echo "     Event: Task Status Updated"
echo ""
echo ""
echo "  Opção B — Marcar Manualmente (Retrospectivo)"
echo "  ────────────────────────────────────────────"
echo "  1. Marcar tarefa específica:"
echo "     python3 ~/Scripts/mark_teve_alteracao_batch.py --task-ids 86ahdcp2a"
echo ""
echo "  2. Marcar todas da lista:"
echo "     python3 ~/Scripts/mark_teve_alteracao_batch.py --all"
echo ""
echo ""
echo "  Opção C — Menu Interativo"
echo "  ───────────────────────────"
echo "  python3 ~/Scripts/teve_alteracao_menu.py"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 Documentação:"
echo "  • Quick Guide: cat ~/Scripts/README_TEVE_ALTERACAO.md"
echo "  • Tech Docs:   cat ~/Scripts/SETUP_AUTO_ALTERACAO.md"
echo "  • Summary:     cat ~/Scripts/AUTOMACAO_TEVE_ALTERACAO_SUMARIO.md"
echo ""
